Couple of Zeek plugin updates.
zeek/spicy pull request #759
Opened 2021-02-18 15:25 UTC by rsmmr

These go with https://github.com/zeek/spicy-analyzers

2021-02-18 16:02 UTC, bbannier requested changes

2021-02-18 16:02 UTC, bbannier commented on zeek/plugin/src/plugin.cc
> +        auto* d = opendir(dir.c_str());
`opendir` and `readdir` need `dirent.h`

2021-02-18 16:02 UTC, bbannier commented on zeek/plugin/src/plugin.cc
> +            if ( strcmp(dp->d_name, "..") == 0 || strcmp(dp->d_name, ".") == 0 )
Needs `cstring`.

2021-02-18 16:02 UTC, bbannier commented on tests/Scripts/have-zeek-plugin
> +    test "$(spicy-config --zeek-version-number)" -ge "${min_version}"
Yikes, the beauty of untyped programming in shell 😰

2021-02-18 18:44 UTC, rsmmr commented on zeek/plugin/src/plugin.cc
> +            return;
Yep, I caught this after the push and just fixed it already.

2021-02-19 07:43 UTC, rsmmr commented on spicy/toolchain/bin/spicy-config.cc
> +            exit(1);
Ok, I'm cleaning this up.

2021-02-19 07:43 UTC, rsmmr commented on zeek/plugin/include/plugin.h
> +    std::set<hilti::rt::filesystem::path> _loaded_modules;
I tend to use `set` if there's no reason to prefer the unordered version; it's shorter. :)

2021-02-19 07:48 UTC, rsmmr commented on zeek/plugin/src/plugin.cc
> +    _loaded_modules.insert(canonical_path);
I'm realizing we don't even need to the new set if we just track the libraries by canonical path. I'll do that.

2021-02-19 07:50 UTC, rsmmr commented on zeek/plugin/src/plugin.cc
> +        // The following code is adapted from Zeek.
Oh, honestly, I didn't know about filesystem::directory_iterator. I'll use that.

2021-02-22 10:29 UTC, bbannier approved these changes

2021-02-22 13:47 UTC, merged