Add &max-size attribute.
zeek/spicy pull request #785
Opened 2021-02-24 16:20 UTC by bbannier

This patch adds a &max-size field and unit attribute. The attribute
allows setting up a maximum number of bytes a parse step should consume.

It is conceptually similar to the existing &size attribute but differs
from it in that an error is raised only if more than the specified bytes
were extracted (&size enforces that exactly the specified number of
bytes is extracted).

@max-size cannot be used together with &size.

Closes #767.

2021-02-24 16:22 UTC, bbannier commented on spicy/toolchain/src/compiler/codegen/parser-builder.cc
> +            length = size;
This or the finalizer code currently triggers an HILTI error with the following unit decl,

```.ruby
type Foo = unit {
    xs: bytes &eod;
} &max-size=1;
```

We also should add tests for this (probably similar to the field-level tests).

2021-02-24 16:22 UTC, bbannier commented on spicy/toolchain/src/compiler/parser/scanner.ll
> +attribute \&(bit-order|byte-order|chunked|convert|count|cxxname|default|eod|internal|ipv4|ipv6|length|max-size|no-emit|nosub|on-heap|optional|originator|parse-at|parse-from|priority|requires|responde
Still need to add the attribute to the docs.

2021-02-25 12:00 UTC, bbannier commented on tests/spicy/types/unit/unit-max-size-fail.spicy
> +# FIXME(bbannier): This currently triggers a bus error, at leats on macos-10.15.7.
This needs to be fixed.

2021-02-25 12:00 UTC, bbannier commented on tests/spicy/types/unit/field-max-size-fail.spicy
> +# @TEST-EXEC-FAIL: spicyc -j %INPUT >>output 2>&1
With this branch rebased onto `master` no diagnostic is triggered here as of 28733d55e388050bffd2d702f257f5812c1db20b.

2021-02-25 15:56 UTC, bbannier commented on tests/spicy/types/unit/field-max-size-fail.spicy
> +# @TEST-EXEC-FAIL: spicyc -j %INPUT >>output 2>&1
Still needs a rebase on the fix for #791.

2021-02-26 10:14 UTC, rsmmr requested changes

2021-02-26 10:14 UTC, rsmmr commented on spicy/toolchain/src/compiler/codegen/parser-builder.cc
> +
As we just talked about, this isn't reliably triggering an error in all cases, let's trigger it here directly.

2021-02-26 11:16 UTC, bbannier commented on doc/programming/parsing.rst
> +``&size=EXPR`` or ``&max-size=EXPR`` attribute that specifies the
I split this into two sections now, one for parsing fields with known size and one for `&max-size` as a defensive mechanism.

2021-03-01 07:57 UTC, rsmmr submitted a review, later dismissed

2021-03-01 07:57 UTC, rsmmr commented on doc/programming/parsing.rst
> +On its own, parser place no intrinsic upper limit on the size of variable-size
```suggestion
On its own, parsers place no intrinsic upper limit on the size of variable-size
```

2021-03-01 07:57 UTC, rsmmr commented on doc/programming/parsing.rst
> +triggered.
I'd move this to above just before "This attributes works on top ...".

2021-03-01 07:57 UTC, rsmmr commented on doc/programming/parsing.rst
> +control parsing.
```suggestion
control parsing. Example:
```

2021-03-01 07:57 UTC, rsmmr commented on spicy/toolchain/src/compiler/codegen/parser-builder.cc
> +                pb->parseError("parsing not done with &max-size bytes", a->meta());
```suggestion
                pb->parseError("parsing not done within &max-size bytes", a->meta());
```

2021-03-01 07:57 UTC, rsmmr commented on spicy/toolchain/src/compiler/codegen/parser-builder.cc
> +            pushBuilder(exceeded, [&]() { pb->parseError("parsing not done with &max-size bytes", a->meta()); });
```suggestion
            pushBuilder(exceeded, [&]() { pb->parseError("parsing not done within &max-size bytes", a->meta()); });
```

2021-03-01 10:15 UTC, merged